name: fault_tracking_frontend
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  camera: ^0.10.5+2
  path_provider: ^2.0.9
  path: ^1.8.0
  mobx: ^2.2.0
  flutter_mobx: ^2.0.6+5
  json_serializable: ^6.7.1
  mobx_codegen: ^2.3.0
  build_runner: ^2.4.6
  idb_sqflite: ^1.3.1
  image_picker_web: ^3.0.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  very_good_analysis: ^5.0.0+1


# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

